spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: lavitreegg@gmail.com
    password: grupo1egg2021
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:mysql://doadmin:3JhkyhEvgBrpE4Dr@db-mysql-nyc3-26559-do-user-8784587-0.b.db.ondigitalocean.com:25060/defaultdb?ssl-mode=REQUIRED
    username: doadmin
    password: 3JhkyhEvgBrpE4Dr
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
server:
  port: 25060
