spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: lavitreegg@gmail.com
    password: grupo1egg2021
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true