spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: lavitreegg@gmail.com
    password: grupo1egg2021
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
   url: jdbc:sqlserver://emirmoretti.database.windows.net:1433;database=lavitreedb;user=emir@emirmoretti;password={lavitreedb1234567!};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
server:
  port: 8080
